[pytest]
addopts = -v -s --alluredir=./allure-results --clean-alluredir -p no:cacheprovider --import-mode=importlib
pythonpath = .
markers =
    smoke: Run smoke tests
    dqc: Run Data Quality Control assertions
    logic: Run Financial Logic assertions
    kline_api: Run Kline data platform API tests
    binance_full_api: Run Binance Full platform API tests
    coinglass_api: Run CoinGlass platform API tests
    factor_data_api: Run Factor Data platform API tests
    binance_usdm_api: Run internal Binance USDM ranking API tests
    open_interest_api: Run Open Interest platform API tests
    performance: Run API performance baseline tests
testpaths = tests
